
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DB
{

using System;
    using System.Collections.Generic;
    
public partial class Payment
{

    public long ID { get; set; }

    public long ShipmentGroupMemberID { get; set; }

    public long ShipmentGroupID { get; set; }

    public long PayorID { get; set; }

    public decimal Amount { get; set; }

    public int PaymentModeID { get; set; }

    public int PaymentCurrencyID { get; set; }

    public long ReceivedBy { get; set; }

    public System.DateTime Created { get; set; }

    public Nullable<System.DateTime> Deleted { get; set; }



    public virtual Currency Currency { get; set; }

    public virtual PaymentMode PaymentMode { get; set; }

    public virtual ShipmentGroupMember ShipmentGroupMember { get; set; }

    public virtual ShipmentGroup ShipmentGroup { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
