
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DB
{

using System;
    using System.Collections.Generic;
    
public partial class ShipmentGroupMember
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShipmentGroupMember()
    {

        this.Payments = new HashSet<Payment>();

    }


    public long ID { get; set; }

    public long MemberID { get; set; }

    public long ShipmentGroupID { get; set; }

    public long ParcelID { get; set; }

    public Nullable<bool> IsFacilitator { get; set; }

    public long DomesticAddressID { get; set; }

    public System.DateTime ConsentedOn { get; set; }

    public Nullable<System.DateTime> ShipmentReceivedAtOrigin { get; set; }

    public Nullable<System.DateTime> DispatchedDomestically { get; set; }

    public Nullable<System.DateTime> DomesticallyReceived { get; set; }

    public decimal ShipmentWeight { get; set; }

    public Nullable<decimal> InternationalShipmentCost { get; set; }

    public Nullable<decimal> DomesticShipmentCost { get; set; }

    public Nullable<decimal> FacilitationFee { get; set; }

    public decimal AppServiceFee { get; set; }

    public decimal TotalPayable { get; set; }

    public bool PayableReceived { get; set; }

    public Nullable<System.DateTime> Completed { get; set; }

    public Nullable<System.DateTime> LastUpdatedOn { get; set; }

    public bool GoodToGo { get; set; }

    public Nullable<bool> ShareDetailsWithMembers { get; set; }

    public System.DateTime Created { get; set; }

    public Nullable<System.DateTime> Deleted { get; set; }



    public virtual Address Address { get; set; }

    public virtual Parcel Parcel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payment> Payments { get; set; }

    public virtual ShipmentGroup ShipmentGroup { get; set; }

    public virtual User User { get; set; }

}

}
