
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DB
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.ParcelItems = new HashSet<ParcelItem>();

        this.Parcels = new HashSet<Parcel>();

        this.Payments = new HashSet<Payment>();

        this.Payments1 = new HashSet<Payment>();

        this.ShipmentGroupMembers = new HashSet<ShipmentGroupMember>();

        this.ShipmentGroupParcels = new HashSet<ShipmentGroupParcel>();

        this.ShipmentGroups = new HashSet<ShipmentGroup>();

    }


    public long ID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string Surname { get; set; }

    public string Gender { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<long> PictureID { get; set; }

    public Nullable<long> AddressID { get; set; }

    public bool Subscribed { get; set; }

    public bool Verified { get; set; }

    public bool Active { get; set; }

    public System.DateTime Created { get; set; }

    public Nullable<System.DateTime> Deleted { get; set; }



    public virtual Address Address { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ParcelItem> ParcelItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Parcel> Parcels { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payment> Payments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payment> Payments1 { get; set; }

    public virtual Picture Picture { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShipmentGroupMember> ShipmentGroupMembers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShipmentGroupParcel> ShipmentGroupParcels { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShipmentGroup> ShipmentGroups { get; set; }

}

}
